stages:
  - build
  - package
  - deploy

.ubuntu-18.04:
  tags: [ linux, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-ubuntu18.04

.windows:
  tags: [ windows, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:devel-windows


.gcc8: &gcc8
  CC: gcc-8
  CXX: g++-8

.msvc15.9: &msvc15_9
  VSDevEnv -arch=amd64 -vcvars_ver="14.16"

.debug: &debug
  CMAKE_BUILD_TYPE: Debug

.release: &release
  CMAKE_BUILD_TYPE: Release


.build ubuntu-18.04:
  extends: .ubuntu-18.04
  stage: build
  artifacts:
    paths:
      - build
    expire_in: 1 day
  script:
    - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" -G Ninja -DCMAKE_SUPPRESS_REGENERATION=ON -DCMAKE_SKIP_PACKAGE_ALL_DEPENDENCY=ON
    - ninja -C build

.build windows:
  extends: .windows
  stage: build
  artifacts:
    paths:
      - build
    expire_in: 1 day
  script:
    - cmake -Bbuild "-H." -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" -G Ninja -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_DIR/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="$env:VCPKG_TRIPLET" -DCMAKE_SUPPRESS_REGENERATION=ON -DCMAKE_SKIP_PACKAGE_ALL_DEPENDENCY=ON
    - ninja -C build

build ubuntu-18.04:
  extends: .build ubuntu-18.04
  variables:
    <<: [ *gcc8, *release ]
  before_script:
    - . /etc/profile.d/robofish.sh
    - gitlab-fetch-artifacts bioroboticslab%2Fbiotracker%2Finterfaces master package%20ubuntu-18.04
    - cmake-integrate-package biotracker-interfaces

build windows:
  extends: .build windows
  variables:
    <<: [ *release ]
  before_script:
    - . $Profile
    - *msvc15_9
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Finterfaces master package%20windows
    - CMake-Integrate-Package biotracker-interfaces

build windows[debug]:
  extends: .build windows
  variables:
    <<: [ *debug ]
  before_script:
    - . $Profile
    - *msvc15_9
    - GitLab-Fetch-Artifacts bioroboticslab%2Fbiotracker%2Finterfaces master package%20windows%5bdebug%5d
    - CMake-Integrate-Package biotracker-interfaces

.package: &package
  stage: package
  artifacts:
    paths:
      - build/*.tar.xz
    expire_in: 1 week
  script:
    - ninja -C build package

package ubuntu-18.04:
  extends: .ubuntu-18.04
  dependencies:
    - build ubuntu-18.04
  <<: *package

package windows:
  extends: .windows
  dependencies:
    - build windows
  <<: *package

package windows[debug]:
  extends: .windows
  dependencies:
    - build windows[debug]
  <<: *package


trigger dependents:
 extends: .ubuntu-18.04
 stage: deploy
 script:
    - . /etc/profile.d/robofish.sh
    - gitlab-trigger-pipeline bioroboticslab%2Fbiotracker%2Fbiotracker $CI_JOB_TOKEN master
