exec_program("git" ${CMAKE_CURRENT_SOURCE_DIR} ARGS "log --pretty=format:%h -n 1" OUTPUT_VARIABLE CURRENT_GIT_HASH)

add_definitions(-DCURRENT_GIT_HASH="${CURRENT_GIT_HASH}")

if("$ENV{USERNAME}" STREQUAL "ContainerAdministrator")
    # Note: This is a workaround for Qt5's "moc" in Windows Docker getting
    #       "System cannot find the file" errors when trying to read
    #       files generated by "configure_file" in conventional directories.
    set(METADATA_DIR "$ENV{TMP}/${TN}")
else()
    set(METADATA_DIR "${CMAKE_CURRENT_BINARY_DIR}")
endif()

add_library (${TN} MODULE)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/plugin.json.in ${METADATA_DIR}/plugin.json)
target_include_directories(${TN} PRIVATE ${METADATA_DIR})

set_target_properties(${TN} PROPERTIES PREFIX "")
set_target_properties(${TN} PROPERTIES OUTPUT_NAME ${TN})
set_target_properties(${TN} PROPERTIES AUTOMOC ON AUTOUIC ON AUTORCC ON)
set_target_properties(${TN} PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED YES
    CXX_EXTENSIONS NO
)

target_link_libraries (${TN} BT_Utility)